backend:
  name: git-gateway
  branch: master
media_folder: static/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    editor:
      preview: false
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Hero heading', name: 'heroHeading', widget: 'string' }
          - { label: 'Hero description', name: 'heroDescription', widget: 'string' }
          - { label: 'Features heading', name: 'featuresHeading', widget: 'string' }
          - { label: 'Feature one', name: 'featureOne', widget: 'string' }
          - { label: 'Feature two', name: 'featureTwo', widget: 'string' }
          - { label: 'Feature three', name: 'featureThree', widget: 'string' }
          - { label: 'Beacon heading', name: 'beaconHeading', widget: 'string' }
          - { label: 'Deacon description', name: 'beaconDescription', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Test dan test', name: 'dan', widget: 'string' }
      - label: 'Product'
        name: 'name'
        file: 'content/product.md'
        fields:
          - { label: 'Hero heading', name: 'heroHeading', widget: 'string' }
          - { label: 'Hero description', name: 'heroDescription', widget: 'string' }
          - { label: 'Product overview heading', name: 'productOverviewHeading', widget: 'string' }
          - { label: 'Key features heading', name: 'keyFeaturesHeading', widget: 'string' }
          - { label: 'Key features description', name: 'keyFeaturesDescription', widget: 'string' }
          - { label: 'Key feature heading1', name: 'keyFeatureHeading1', widget: 'string' }
          - { label: 'Key feature description1', name: 'keyFeatureDescription1', widget: 'string' }
          - { label: 'Key feature heading2', name: 'keyFeatureHeading2', widget: 'string' }
          - { label: 'Key feature description2', name: 'keyFeatureDescription2', widget: 'string' }
          - { label: 'Key feature heading3', name: 'keyFeatureHeading3', widget: 'string' }
          - { label: 'Key feature description3', name: 'keyFeatureDescription3', widget: 'string' }
          - { label: 'Key feature heading4', name: 'keyFeatureHeading4', widget: 'string' }
          - { label: 'Key feature description4', name: 'keyFeatureDescription4', widget: 'string' }
          - { label: 'Key feature heading5', name: 'keyFeatureHeading5', widget: 'string' }
          - { label: 'Key feature description5', name: 'keyFeatureDescription5', widget: 'string' }
          - { label: 'Key feature heading6', name: 'keyFeatureHeading6', widget: 'string' }
          - { label: 'Key feature description6', name: 'keyFeatureDescription6', widget: 'string' }
          - { label: 'Key feature heading7', name: 'keyFeatureHeading7', widget: 'string' }
          - { label: 'Key feature description7', name: 'keyFeatureDescription7', widget: 'string' }
          - { label: 'Key feature heading8', name: 'keyFeatureHeading8', widget: 'string' }
          - { label: 'Key feature description8', name: 'keyFeatureDescription8', widget: 'string' }
          - { label: 'Integrated video conferencing heading', name: 'integratedVideoConferencingHeading', widget: 'string' }
          - { label: 'Integrated video conferencing description', name: 'integratedVideoConferencingDescription', widget: 'text' }
          - { label: 'Integrated video conferencing cta label', name: 'integratedVideoConferencingCTALabel', widget: 'string' }
  - label: 'Blog'
    name: 'blog'
    editor:
      preview: false
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
