backend:
  name: git-gateway
  branch: master
media_folder: static/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    editor:
      preview: false
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Hero heading', name: 'heroHeading', widget: 'string' }
          - { label: 'Hero description', name: 'heroDescription', widget: 'string' }
          - { label: 'Features heading', name: 'featuresHeading', widget: 'string' }
          - { label: 'Feature one', name: 'featureOne', widget: 'string' }
          - { label: 'Feature two', name: 'featureTwo', widget: 'string' }
          - { label: 'Feature three', name: 'featureThree', widget: 'string' }
          - { label: 'Beacon heading', name: 'beaconHeading', widget: 'string' }
          - { label: 'Deacon description', name: 'beaconDescription', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Test dan test', name: 'dan', widget: 'string' }
      - label: 'Product'
        name: 'name'
        file: 'content/product.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hero heading', name: 'hero__heading', widget: 'string' }
          - { label: 'Hero description', name: 'hero__description', widget: 'string' }
          - { label: 'Product overview heading', name: 'productOverview__heading', widget: 'string' }
          - { label: 'Product overview CTA', name: 'productOverview__cta', widget: 'string' }
          - { label: 'Key features heading', name: 'keyFeatures__heading', widget: 'string' }
          - { label: 'Key features description', name: 'keyFeatures__description', widget: 'string' }
          - { label: 'Key features subheading', name: 'keyFeatures__subheading', widget: 'string' }
          - label: 'Key features'
            name: 'keyFeatures'
            widget: 'list'
            fields:
              - { label: Feature name, name: featureName, widget: string }
              - { label: Feature description, name: featureDescription, widget: string }
          - { label: 'Integrated video conferencing heading', name: 'integratedVideoConferencing__heading', widget: 'string' }
          - { label: 'Integrated video conferencing description', name: 'integratedVideoConferencing__description', widget: 'text' }
          - { label: 'Integrated video conferencing cta label', name: 'integratedVideoConferencing__ctaLabel', widget: 'string' }
          - { label: 'platformFlexibility__heading', name: 'Platform flexibility heading', wiget: 'string' }
          - { label: 'platformFlexibility__description', name: 'Platform flexibility description', wiget: 'text' }
          - label: 'Logo'
            name: 'logo'
            widget: 'list'
            fields:
              - { label: file, name: file, widget: string }
              - { label: name, name: name, widget: string }
      - label: 'Company'
        name: 'company'
        file: 'content/company.md'
        fields:
          - label: 'Team members'
            name: 'testimonials'
            widget: 'list'
            fields:
              - { label: Picture, name: picture, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - label: 'Product advisory board members'
            name: 'productAdvisoryBoardMembers'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Company, name: company, widget: string }
              - { label: LinkedIn, name: linkedIn, widget: string }
          - label: 'Values'
            name: 'values'
            widget: 'list'
            fields:
              - { label: Value, name: value, widget: string }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hero heading', name: 'hero__heading', widget: 'string' }
          - { label: 'Hero description', name: 'hero__description', widget: 'string' }
          - { label: 'Team heading', name: 'team__heading', widget: 'string' }
          - { label: 'Team description', name: 'team__description', widget: 'string' }
          - { label: 'Product advisory board heading', name: 'productAdvisoryBoard__heading', widget: 'string' }
          - { label: 'Product advisory board description', name: 'productAdvisoryBoard__description', widget: 'string' }
          - { label: 'Working at alucio heading', name: 'workingAtAlucio__heading', widget: 'string' }
          - { label: 'Working at alucio description', name: 'workingAtAlucio__description', widget: 'string' }
          - { label: 'What we value heading', name: 'whatWeValue__heading', widget: 'string' }
          - { label: 'What we value linkedin label', name: 'whatWeValue__linkedinLabel', widget: 'string' }
          - { label: 'What we value linkedin href', name: 'whatWeValue__linkedinHref', widget: 'string' }
          - { label: 'What we value glassdoor label', name: 'whatWeValue__glassdoorLabel', widget: 'string' }
          - { label: 'What we value glassdoor href', name: 'whatWeValue__glassdoorHref', widget: 'string' }
          - { label: 'Join us heading', name: 'joinUs__heading', widget: 'string' }
          - { label: 'Join us description', name: 'joinUs__description', widget: 'string' }
          - { label: 'Press heading', name: 'press__heading', widget: 'string' }
          - { label: 'Press description', name: 'press__description', widget: 'string' }
          - { label: 'Pledge one percentage heading', name: 'pledgeOnePercentage__heading', widget: 'string' }
          - { label: 'Pledge one percentage description', name: 'pledgeOnePercentage__description', widget: 'string' }
          - { label: 'Pledge one percentage cta label', name: 'pledgeOnePercentage__CtaLabel', widget: 'string' }
      - label: 'Experience'
        name: 'experience'
        file: 'content/experience.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hero description', name: 'hero__description', widget: 'string' }
          - { label: 'User feedback heading', name: 'userFeedback__heading', widget: 'string' }
          - { label: 'User feedback description', name: 'userFeedback__description', widget: 'string' }
          - label: 'Quotes'
            name: 'quotes'
            widget: 'list'
            fields:
              - { label: Quote, name: quote, widget: string }
          - { label: 'Partners heading', name: 'partners__heading', widget: 'string' }
          - { label: 'Partners description', name: 'partners__description', widget: 'string' }
          - label: 'partners logo'
            name: 'partners__logo'
            widget: 'list'
            fields:
              - { label: file, name: file, widget: string }
              - { label: name, name: name, widget: string }
          - { label: 'Partnering heading', name: 'partnering__heading', widget: 'string' }
          - { label: 'Partnering description', name: 'partnering__description', widget: 'string' }
      - label: 'Perspectives'
        name: 'perspectives'
        file: 'content/perspectives.md'
        fields:
          - { label: 'Hero heading', name: 'hero__heading', widget: 'string' }
          - { label: 'Hero description', name: 'hero__description', widget: 'string' }
          - label: 'Articles'
            name: 'articles'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string'}
              - { label: 'Publication', name: 'publication', widget: 'string'}
              - { label: 'Date', name: 'date', widget: 'string'}
          - label: 'research'
            name: 'research'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string'}
              - { label: 'Author', name: 'author', widget: 'string'}
              - { label: 'Date', name: 'date', widget: 'string'}

  - label: 'Blog'
    name: 'blog'
    editor:
      preview: false
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
