backend:
  name: git-gateway
  branch: master
media_folder: public/static
public_folder: /static
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: pages
    editor:
      preview: false
    label: Pages
    files:
      - label: Home
        name: home
        file: content/home.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Hero heading
            name: heroHeading
            widget: string
          - label: Hero description
            name: heroDescription
            widget: text
          - label: Hero video
            name: heroVideo
            widget: file
            media_library:
              config:
                multiple: false
          - label: Features heading
            name: featuresHeading
            widget: string
          - label: Feature one
            name: featureOne
            widget: string
          - label: 'Feature one icon '
            name: featureOneIcon
            widget: file
            media_library:
              config:
                multiple: false
          - label: Feature two
            name: featureTwo
            widget: string
          - label: 'Feature two icon '
            name: featureTwoIcon
            widget: file
            media_library:
              config:
                multiple: false
          - label: Feature three
            name: featureThree
            widget: string
          - label: 'Feature three icon '
            name: featureThreeIcon
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon heading
            name: beaconHeading
            widget: string
          - label: Beacon description
            name: beaconDescription
            widget: text
          - label: Beacon CTA label
            name: beaconCtaLabel
            widget: string
          - label: Beacon CTA URL
            name: beaconCtaUrl
            widget: string
          - label: Beacon info graphic icon 1
            name: beaconInfoGraphicIcon1
            required: false
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon info graphic lbl1
            name: beaconInfoGraphicLbl1
            widget: string
          - label: Beacon info graphic icon 2
            name: beaconInfoGraphicIcon2
            required: false
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon info graphic lbl2
            name: beaconInfoGraphicLbl2
            widget: string
          - label: Beacon info graphic icon 3
            name: beaconInfoGraphicIcon3
            required: false
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon info graphic lbl3
            name: beaconInfoGraphicLbl3
            widget: string
          - label: Beacon info graphic icon 4
            name: beaconInfoGraphicIcon4
            required: false
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon info graphic lbl4
            name: beaconInfoGraphicLbl4
            widget: string
          - label: Beacon info graphic icon 5
            name: beaconInfoGraphicIcon5
            required: false
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon info graphic lbl5
            name: beaconInfoGraphicLbl5
            widget: string
          - label: Beacon info graphic icon 6
            name: beaconInfoGraphicIcon6
            required: false
            widget: file
            media_library:
              config:
                multiple: false
          - label: Beacon info graphic lbl6
            name: beaconInfoGraphicLbl6
            widget: string
          - label: CTA heading
            name: ctaHeading
            widget: string
          - label: CTA label
            name: ctaLbl
            widget: string
          - label: CTA URL
            name: ctaUrl
            widget: string
      - label: Product
        name: name
        file: content/product.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Hero heading
            name: hero__heading
            widget: string
          - label: Hero tagline
            name: hero__tagline
            widget: text
          - label: Hero video
            name: hero__video
            widget: file
            media_library:
              config:
                multiple: false
          - label: Hero video thumbnail
            name: hero__videoThumb
            widget: file
            media_library:
              config:
                multiple: false
          - label: Key features heading
            name: keyFeatures__heading
            widget: string
          - label: Key features description
            name: keyFeatures__description
            widget: text
          - label: Key features subheading
            name: keyFeatures__subheading
            widget: string
          - label: Key features
            name: keyFeatures
            widget: list
            fields:
              - label: Feature name
                name: featureName
                widget: string
              - label: Feature description
                name: featureDescription
                widget: text
              - label: 'Feature icon '
                name: featureIcon
                widget: file
                media_library:
                  config:
                    multiple: false
          - label: Integrated video conferencing heading
            name: integratedVideoConferencing__heading
            widget: string
          - label: Integrated video conferencing description
            name: integratedVideoConferencing__description
            widget: text
          - label: Integrated video conferencing cta label
            name: integratedVideoConferencing__ctaLabel
            widget: string
          - label: Platform flexibility heading
            name: platformFlexibility__heading
            widget: string
          - label: Platform flexibility description
            name: platformFlexibility__description
            widget: text
      - label: Company
        name: company
        file: content/company.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Hero heading
            name: hero__heading
            widget: string
          - label: Hero description
            name: hero__description
            widget: text
          - label: Team heading
            name: team__heading
            widget: string
          - label: Team description
            name: team__description
            widget: string
          - label: Team members
            name: teamMembers
            widget: list
            fields:
              - label: Picture
                name: picture
                widget: image
                required: false
              - label: Name
                name: name
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Title 2
                name: title2
                widget: string
          - label: Product advisory board heading
            name: productAdvisoryBoard__heading
            widget: string
          - label: Product advisory board description
            name: productAdvisoryBoard__description
            widget: text
          - label: Product advisory board members
            name: advisoryBoardMembers
            widget: list
            fields:
              - label: Picture
                name: picture
                widget: image
                required: false
              - label: Name
                name: name
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Company
                name: company
                widget: string
              - label: LinkedIn
                name: linkedIn
                widget: string
          - label: Working at alucio heading
            name: workingAtAlucio__heading
            widget: string
          - label: Working at alucio description
            name: workingAtAlucio__description
            widget: text
          - label: What we value heading
            name: whatWeValue__heading
            widget: string
          - label: Values
            name: values
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: string
          - label: Join us heading
            name: joinUs__heading
            widget: string
          - label: Join us description
            name: joinUs__description
            widget: text
          - label: Job openings
            name: jobOpenings
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Link
                name: link
                widget: string
          - label: Press heading
            name: press__heading
            widget: string
          - label: Press description
            name: press__description
            widget: text
          - label: Press releases
            name: pressReleases
            widget: list
            fields:
              - label: Date
                name: date
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Link
                name: link
                widget: string
          - label: Pledge one percentage heading
            name: pledgeOnePercentage__heading
            widget: string
          - label: Pledge one percentage description
            name: pledgeOnePercentage__description
            widget: text
          - label: Pledge one percentage cta label
            name: pledgeOnePercentage__ctaLabel
            widget: string
          - label: Pledge one percentage cta link
            name: pledgeOnePercentage__ctaLink
            widget: string
          - label: Diversity heading
            name: diversity__heading
            widget: string
          - label: Diversity description
            name: diversity__description
            widget: markdown
          - label: Diversity image
            name: diversity__image
            widget: file
            media_library:
              config:
                multiple: false
          - label: Contact heading
            name: contact__heading
            widget: string
          - label: Contact column one heading
            name: contact__colOneSubheading
            widget: string
          - label: Contact column one content
            name: contact__colOneContent
            widget: markdown
          - label: Contact column two heading
            name: contact__colTwoSubheading
            widget: string
          - label: Contact column two content
            name: contact__colTwoContent
            widget: markdown
      - label: Experience
        name: experience
        file: content/experience.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Hero heading
            name: hero__heading
            widget: string
          - label: Hero description
            name: hero__description
            widget: text
          - label: User feedback heading
            name: userFeedback__heading
            widget: string
          - label: User feedback description
            name: userFeedback__description
            widget: text
          - label: Quotes
            name: quotes
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: string
      - label: Partners
        name: partners
        file: content/partners.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Hero heading
            name: hero__heading
            widget: string
          - label: Hero description
            name: hero__description
            widget: text
          - label: Intro
            name: intro
            widget: text
          - label: Partner logos
            name: logos
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: File
                name: src
                widget: image
                required: false
          - label: Partnering heading
            name: partnering__heading
            widget: string
          - label: Partnering description
            name: partnering__description
            widget: markdown
      - label: Perspectives
        name: perspectives
        file: content/perspectives.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Hero heading
            name: hero__heading
            widget: string
          - label: Hero description
            name: hero__description
            widget: text
          - label: Intro
            name: intro
            widget: text
          - label: Articles
            name: articles
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Link
                name: link
                widget: string
              - label: Publication
                name: publication
                widget: string
              - label: Date
                name: date
                widget: string
          - label: Research
            name: research
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Link
                name: link
                widget: string
              - label: Author
                name: author
                widget: string
              - label: Date
                name: date
                widget: string
  - label: Blog
    name: blog
    editor:
      preview: false
    folder: content/blogPosts
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
      - label: Body
        name: body
        widget: markdown
  - label: General pages
    name: generalPages
    editor:
      preview: false
    folder: content/general
    create: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Content
        name: content
        widget: markdown
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: Navigation
        name: navigation
        file: content/navigation.md
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: URL
                name: url
                widget: string
      - label: Footer
        name: footer
        file: content/footer.md
        fields:
          - label: Column one links
            name: columnOne__links
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: URL
                name: url
                widget: string
          - label: Column two links
            name: columnTwo__links
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: URL
                name: url
                widget: string
          - label: Social media links
            name: socialMediaLinks
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: URL
                name: url
                widget: string
          - label: Copyright text
            name: copyrightText
            widget: string
